chore:fixes

diff --git a/.github/workflows/ci-stylus-gas-bench.yml b/.github/workflows/ci-stylus-gas-bench.yml
--- a/.github/workflows/ci-stylus-gas-bench.yml
+++ b/.github/workflows/ci-stylus-gas-bench.yml
@@ -50,18 +50,25 @@ jobs:
         run: ./scripts/nitro-testnode.sh -d -i
       - name: run benches
         run: |
-          # Set up environment variables
+       # Set up environment variables
           echo "RPC_URL=http://localhost:8547" >> $GITHUB_ENV
           echo "PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" >> $GITHUB_ENV
           echo "WALLER_ADDRESS=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266" >> $GITHUB_ENV
-
+          # Deploy Mock Pyth Contract
           cd pyth-mock-solidity
           deployed_to=$(forge script ./script/MockPyth.s.sol:MockPythScript \
             --rpc-url "$RPC_URL" \
             --private-key "$PRIVATE_KEY" \
             --broadcast \
-            | grep -oP '(?<=Pyth contract address: )0x[a-fA-F0-9]{40}' | tail -n 1)
-          echo "MOCK_PYTH_ADDRESS=$deployed_to" >> $GITHUB_ENV
+            | tee /dev/stderr | grep -oP '(?<=Pyth contract address: )0x[a-fA-F0-9]{40}' | tail -n 1)
+          if [[ -z "$deployed_to" ]]; then
+            echo "Error: MOCK_PYTH_ADDRESS not found!" >&2
+            exit 1
+          fi
+          echo "MOCK_PYTH_ADDRESS=$deployed_to" | tee -a $GITHUB_ENV
           cd ..
-          
+          # Debugging: Show environment variables
+          echo "Exported Variables:"
+          env | grep -E "RPC_URL|PRIVATE_KEY|WALLER_ADDRESS|MOCK_PYTH_ADDRESS"
+          # Run Benches 
           ./scripts/bench.sh
